safe: false

# build settings
markdown: kramdown
highlighter: rouge
lsi: false
permalink: /:title

title: "Janyway's Page"
description: "彼此莫相忘，不负好时光"
baseurl: ""
url: "http://janyway.com" # replace by your site's url
twitter_username: your-name
github_username:  janyway # (your name)
accent: "#BFEFFF" # accent color for blog column

author: "Janyway Zhang"
address: "Yinhe Mansion, Jinan, China"
email: "janyway@outlook.com"
QQ: "547096704"

# google analytics tracking code, please change the value
# g_analytics: ""

# language settings
isolang: en

# exclude files
exclude:
  - LICENSE
  - README.md
